# Generated by Django 4.2.7 on 2023-11-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('nextRepetition', models.IntegerField()),
                ('questionNumber', models.IntegerField()),
                ('subject', models.TextField()),
                ('link', models.URLField()),
                ('correctOption', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
