# Generated by Django 4.1.13 on 2023-11-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
