# Generated by Django 4.1.13 on 2023-12-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='dcount',
            field=models.IntegerField(default=0),
        ),
    ]
